[package]
name = "mpc"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.32.1"
env_logger = "0.11.8"
rodio = { version = "0.21.0", default-features = false, features = ["symphonia-all", "playback"] }
